version: '3'
services:
  nginx:
    build:
      context: .docker/nginx
      dockerfile: Dockerfile-nginx
    container_name: nginx
    ports:
      - "82:80"
    restart: always
    volumes:
      - ./backend:/var/www
    depends_on:
      - php
    networks:
      - base
  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile-php
    container_name: php
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    networks:
      - base
  mysql:
    build:
      context: .docker/mysql
      dockerfile: Dockerfile-mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-base
      MYSQL_USER: mengue
      MYSQL_PASSWORD: 123
    ports:
      - "3302:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    networks:
      - base

networks:
  base:
    driver: bridge